### ISSUE TITLE
Background for Cosmos, Life, etc. are not all unique to topic area

### ISSUE THREAD

**Issue by MedicalTest** [alterm4nn/ChronoZoom#1054]
Issue:  Background for Cosmos, Life, etc. are not all unique to topic area

![panoply](https://f.cloud.github.com/assets/5091775/1103979/825ed2de-18d4-11e3-825a-18ae8d3b112d.png)

Steps:
     1.  Launch ChronoZoom  (http://chronozoom.com)
     2.  Click on Cosmos (and you get space, as expected.
     3.  Click on Life or other menu topics

Actual result:  Cosmos, cosmos, cosmos…  (see attached, “panoply.png”)

Expected result:  Cosmos background for Cosmos, Earth for Earth…Life…and others should have their own background in context with the menu topic.
 
Configuration details
Date: 9/3/2013
OS: iOS
Device(s): iPad (4th Generation), Win8 Tablet (Intel)
Browser(s):   all supported

**Comment by alterm4nn** [comment]
Custom background feature was implemented, it covers suggested change
