### ISSUE TITLE
Authoring: Save Exhibit (4)

### ISSUE THREAD

**Issue by mnourminskaya** [alterm4nn/ChronoZoom#1195]
# Problem
ChronoZoom has dialog for modifying Exhibits with a child dialog for Artifacts which does not save individual artifacts before the entire Exhibit is saved. This means that the logic to check an Exhibit Artifact such as the media URL is not checked before all the Artifacts are saved with the Exhibit. This leads to confusion for the user who does not know what to do when the Exhibit will not save, and in frustration abandon editing the Exhibit and report loss of data.
# Solution
Validate Artifact before returning to Exhibit as blocking operation.

**Comment by alterm4nn** [comment]
close as fixed tong time ago
