### ISSUE TITLE
Funky button behavior on homepage

### ISSUE THREAD

**Issue by ericschultz** [alterm4nn/ChronoZoom#1376]
I've noticed that on the homepage, the buttons for featured content sometimes link to the homepage, not the expected content. It's not entirely clear to me but I thought I'd put this down in the issues so people knew about them.

I'm running Mozilla Firefox 36.0a2 on Windows 8.1

**Comment by NeilCresswell** [comment]
Hi Eric,

A quick update: I've submitted a pull request today that should hopefully address this issue. It should go live in the next couple of days.

Regards,
Neil.

**Comment by alterm4nn** [comment]
@ericschultz can you confirm that issue is fixed now? I cannot reproduce it anymore

**Comment by ericschultz** [comment]
I've tested it again. I don't remember exactly how the problem manifested but I'm not noticing it now.

**Comment by alterm4nn** [comment]
Very good, thanks!
