### ISSUE TITLE
Time Series Menu Bad Text Formatting

### ISSUE THREAD

**Issue by M3tan3rd** [alterm4nn/ChronoZoom#1386]
1) Open Time Series Menu, observe that third entry is badly formatted
Google Chrome Version 40.0.2214.94 m
![image](https://cloud.githubusercontent.com/assets/3171149/6015525/4e49fef8-ab2a-11e4-9374-17069a094be7.png)

**Comment by saekow** [comment]
Thank you Peter!

I confirm the issue also on Chrome Mac Version 40.0.2214.94
Safari Version 8.0.3 does not have it, just a minor issue, see attachment.

**Comment by saekow** [comment]
Minor issue in Safari:
![screen shot 2015-02-02 at 10 26 41 pm](https://cloud.githubusercontent.com/assets/4260951/6015586/2d711b66-ab2b-11e4-858f-60d0f501c457.png)

**Comment by alterm4nn** [comment]
Fixed by @ldebruijn in #1393
