### ISSUE TITLE
The History of Cinnabar

### ISSUE THREAD

**Issue by margotellen** [alterm4nn/ChronoZoom#1405]
My ChronoZoom is not loading Exhibits and artifacts on my PC and not loading at all on my IPad. Need for presentation tomorrow!

**Comment by alterm4nn** [comment]
@margotellen Do you use personal collection or default one (Cosmos etc)?

**Comment by margotellen** [comment]
I think it is personal collection but it is finally working now.

**Comment by margotellen** [comment]
I am trying to create a sibling timeline in my Root timeline and the
program says it intersects with my parent or sibling. My parent is 11,000
B.C.E to A.D. and I have two siblings from 11000 to 6400 B.C.E. I am trying
to create a third one from 10,500 B.C.E to 300 B.C.E. and that is the
response I got. I don't understand why.
