### ISSUE TITLE
Recently published section on homepage is blank

### ISSUE THREAD

**Issue by saekow** [alterm4nn/ChronoZoom#1406]
Recently published section on homepage is blank. The issue happen when not logged in.
I tried different browser, reset cache. Sometimes the section will appear after a long delay.
![screen shot 2015-04-28 at 10 14 46 pm](https://cloud.githubusercontent.com/assets/4260951/7385103/1870ce4e-edf4-11e4-9acb-18928ac71730.png)

**Comment by alterm4nn** [comment]
Resolved
