### ISSUE TITLE
Feature request: Copy and paste exhibits

### ISSUE THREAD

**Issue by saekow** [alterm4nn/ChronoZoom#1410]
In a classroom environment where several students (100+) are creating exhibits, and where the eventual goal is to produce one main timeline with all resulting finished student exhibits, currently instructors can only copy paste entire timelines or share a single timeline with all students.

Sharing a single timeline with all students and inviting students to create exhibits directly on the shared timeline presents a risk since any other students could accidentally erase all alter the entire timeline.

Allowing copy and paste of individual exhibits could improve the situation.

**Comment by alterm4nn** [comment]
I just saw that feature implemented by one of the Fonty's university teams: 
https://github.com/FHICTChronoZoom/ChronoZoom/commit/6fbc8a4a2cfe2df73257bc56eb02710c9fdbf8d9 and https://github.com/FHICTChronoZoom/ChronoZoom/commit/46f37b6f25bee9b000ee6e2505dd6b8cb5df325d

I had no chance to test it, but I think they could make pull request to get this working with current version of ChronoZoom.

**Comment by alterm4nn** [comment]
#1412 verified, changed a bit, and published to production
